[[datasets]]
resolution = 786
batch_size = 1
keep_tokens = 1
enable_bucket = true
min_bucket_reso = 64
max_bucket_reso = 1280
bucket_reso_steps = 32
bucket_no_upscale = true

  [[datasets.subsets]]
  image_dir = '/dataset/projects/my_project/set_01'
  num_repeats = 10
  class_tokens = 'my_project'
  caption_extension = '.txt'